import { Cascadia_Code } from "next/font/google";
import "./globals.css";
import AppNavbar from "@/components/Navbar";

const cascadiaCode = Cascadia_Code({
  variable: "--font-cascadia-code",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${cascadiaCode.variable}  h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <AppNavbar></AppNavbar>
        {children}
      </body>
    </html>
  );
}
